#!/bin/bash

echo "SnoW's Install script!\n\n\n";
echo "Install PHP 7.2";
apt-get update && apt-get upgrade;
apt-get install python-software-properties;
add-apt-repository ppa:ondrej/php;
apt-get update;
apt-get install php7.2;
apt-get install php-pear php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml;

echo "Install Composer:\n\n\n";
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');";
php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;";
php composer-setup.php;
php -r "unlink('composer-setup.php');";
mv composer.phar /usr/local/bin/composer;

echo "Install Laravel:\n\n\n";
composer global require "laravel/installer";
export PATH=$PATH:/var/www/html/vendor/bin;

echo "\n\n Finished :)";
